# Vectors, Matrices, Linear Algebra

In [2]:
from sympy.interactive.printing import init_printing
from sympy import *
import numpy as np 
init_printing(use_unicode=True)


## Objectives:
* Manipulate vectors and matrices
* Solve some linear algebra problems 

## 1.1 Vectors

In [3]:
u = np.array([-1, 2, 3])
v = np.array([1, 2 , 3])
print(u+v)

[0 4 6]


In [4]:
print(u-v)

[-2  0  0]


* Element wise product between two vectors

In [5]:
# elements wise product 
u*v

array([-1,  4,  9])

* dot product

In [6]:
# dot products
np.dot(u,v)

12

* cross product

In [7]:
np.cross(u, v)

array([ 0,  6, -4])

## 1.2 Matrices

In [8]:
M = Matrix([[1,2],[3,4]])
M

⎡1  2⎤
⎢    ⎥
⎣3  4⎦

In [9]:
i, j = symbols('i, j') 

def f(i, j):
    return i**2+j**2

M1 = Matrix(2, 4, f)
M1

⎡0  1  4  9 ⎤
⎢           ⎥
⎣1  2  5  10⎦

In [10]:
print('Cols and Rows of M1 matrix are {} and {}'.format(M1.cols, M1.rows))
print('the second element of row 0 is {}'.format(M1[0, 2]))

Cols and Rows of M1 matrix are 4 and 2
the second element of row 0 is 4


In [11]:
M1[2]

In [12]:
M1[:,2:4]

⎡4  9 ⎤
⎢     ⎥
⎣5  10⎦

In [13]:
a = [1, 2, 3, 4]
M2 = Matrix(2, 2, a)
M2

⎡1  2⎤
⎢    ⎥
⎣3  4⎦

* identity matrix

In [14]:
I = eye(3)
I

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

In [15]:
N = Matrix([[1, -1], [0, 2]])
N

⎡1  -1⎤
⎢     ⎥
⎣0  2 ⎦

* matrix multiplication

In [16]:
M2*N

⎡1  3⎤
⎢    ⎥
⎣3  5⎦

In [17]:
N**3

⎡1  -7⎤
⎢     ⎥
⎣0  8 ⎦

* List comprehension to create new matrix 

In [18]:
Matrix(2, 2, [i*i for i in N])

⎡1  1⎤
⎢    ⎥
⎣0  4⎦

## 1.3 Linear algebra

* transpose of a matrix

In [19]:
transpose(M2)

⎡1  3⎤
⎢    ⎥
⎣2  4⎦

In [20]:
transpose(M1)

⎡0  1 ⎤
⎢     ⎥
⎢1  2 ⎥
⎢     ⎥
⎢4  5 ⎥
⎢     ⎥
⎣9  10⎦

* rank of a matrix

In [21]:
# rank of a matrix
I.rank()

In [22]:
# determinant of a matrix
I.det()

In [23]:
M2.rank()

In [24]:
M2.det()

In [25]:
M2.inv()

⎡-2    1  ⎤
⎢         ⎥
⎣3/2  -1/2⎦

In [26]:
M2**-1

⎡-2    1  ⎤
⎢         ⎥
⎣3/2  -1/2⎦

* eigenvalues

In [27]:
evals = M2.eigenvals()
evals

In [28]:
evals.values()

dict_values([1, 1])

## 2 Exercises


### 2.1 Vector manipulation
* Q 2.1.1 - Define the two vectors
$$c = \begin{bmatrix} 
  \sin(\theta)\cos(\phi) \\
  \sin(\theta)\sin(\phi)\\
  \cos(\theta)
\end{bmatrix}
, 
o = \begin{bmatrix} 
  -\cos(\theta)\cos(\phi) \\
  -\cos(\theta)\sin(\phi)\\
  \sin(\theta)
\end{bmatrix}$$

In [29]:
θ , ϕ = symbols('θ , ϕ')
c = np.array([sin(θ)*cos(ϕ),sin(θ)*sin(ϕ),cos(θ)])
o = np.array([-cos(θ)*cos(ϕ),-cos(θ)*sin(ϕ),sin(θ)])
print ('c =', c)
print ('o =', o)

c = [sin(θ)*cos(ϕ) sin(θ)*sin(ϕ) cos(θ)]
o = [-cos(θ)*cos(ϕ) -sin(ϕ)*cos(θ) sin(θ)]


* Q 2.1.2 - Prove that these vectors are orthogonal 

In [30]:
A = np.dot(o, c)

def function(θ , ϕ):
    f = -sin(θ)*sin(ϕ)**2*cos(θ) - sin(θ)*cos(θ)*cos(ϕ)**2 + sin(θ)*cos(θ)
    return f

function(np.pi/5 , np.pi/3)

In [48]:
#other way :

A = np.dot(o, c)
A.simplify()

* Q2.1.3 - prove that their norm is 1

In [49]:
o_norm = sqrt(np.dot(o,o))
o_norm.simplify()

In [46]:
c_norm = sqrt(np.dot(c,c))
c_norm.simplify()

* Q2.1.3 - Compute the third vector $b$ that is orthogonal to both $o$ and $c$

In [50]:
b = np.cross(c,o)
b

array([sin(θ)**2*sin(ϕ) + sin(ϕ)*cos(θ)**2,
       -sin(θ)**2*cos(ϕ) - cos(θ)**2*cos(ϕ), 0], dtype=object)

### 2.2 Basic matrices computation

Consider the following matrices:
$$
A = \begin{bmatrix} 
  -3 & 2 \\
   0 & 4\\
   1 & -1
\end{bmatrix}
, 
B = \begin{bmatrix} 
  1 & 2 \\
  0 & 1 \\
  1 & 1
\end{bmatrix}
$$
* Q 2.2.1 - Find a matrix $C$ such that $A-2B-C=0$
* Q 2.2.2 - Find a matrix $D$ such that $A+B+C+4D =0$

In [33]:
A = Matrix([[-3, 2], [0, 4], [1, -1]])
B = Matrix([[1, 2],[0,1],[1, 1]])
C = A - 2*B
C

⎡-5  -2⎤
⎢      ⎥
⎢0   2 ⎥
⎢      ⎥
⎣-1  -3⎦

In [34]:
D = (A+B+C)/4
D

⎡-7/4  1/2 ⎤
⎢          ⎥
⎢ 0    7/4 ⎥
⎢          ⎥
⎣1/4   -3/4⎦

### 2.3 Linear system 
Find the following linear system by first using solve and then using matrix representation.

$$
  \begin{cases}
    x_1 + 2x_2 + 3x_3 + 4x_4 &= 25,\\
    -x_2 + x_3 -x_4 &= 5,\\
    x_1 + 2x_2+ 2x_3 &= 20, \\
    2x_1 + 3x_3 &= 19
  \end{cases}
$$



In [36]:
x1, x2, x3, x4 = symbols('x1,x2,x3,x4')

In [55]:
A = Matrix([[1,2,3,4],[0,-1,1,-1],[1,2,2,0],[2,0,3,0]])

In [38]:
X = Matrix([[x1],[x2],[x3],[x4]])

In [39]:
B = Matrix([[25],[5],[20],[19]])

In [40]:
X = A.inv()*B
X

⎡ -2 ⎤
⎢    ⎥
⎢10/3⎥
⎢    ⎥
⎢23/3⎥
⎢    ⎥
⎣-2/3⎦

In [57]:
# other way :

A.solve_least_squares(B)

⎡ -2 ⎤
⎢    ⎥
⎢10/3⎥
⎢    ⎥
⎢23/3⎥
⎢    ⎥
⎣-2/3⎦

### 2.4 Commuting matrices 
In linear algebra, two matrices $A$ and $B$ are said to commute if $A.B = B.A$ and equivalently their commutator $A.B - B.A = 0$.
Find all the matrices that when commutes with matrix 
$A = 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 3 & 0 \\
0 & 0 & 5
\end{bmatrix}
$
can be writen in the form of:
$$
B = \begin{bmatrix}
k_1  & 0 & 0 \\
0 & k_2 & 0 \\
0 & 0 & k_3
\end{bmatrix} , k_1, k_2, k_3 \in \rm I\!R
$$


In [60]:
a11,a12,a13, a21,a22,a23, a31,a32,a33 = symbols('a11,a12,a13, a21,a22,a23, a31,a32,a33')
A = Matrix([[1,0,0],[0,3,0],[0,0,5]])
B = Matrix([[a11,a12,a13],[a21,a22,a23],[a31,a32,a33]])
A,B

⎛⎡1  0  0⎤  ⎡a₁₁  a₁₂  a₁₃⎤⎞
⎜⎢       ⎥  ⎢             ⎥⎟
⎜⎢0  3  0⎥, ⎢a₂₁  a₂₂  a₂₃⎥⎟
⎜⎢       ⎥  ⎢             ⎥⎟
⎝⎣0  0  5⎦  ⎣a₃₁  a₃₂  a₃₃⎦⎠

In [63]:
M = A*B - B*A
M

⎡  0    -2⋅a₁₂  -4⋅a₁₃⎤
⎢                     ⎥
⎢2⋅a₂₁    0     -2⋅a₂₃⎥
⎢                     ⎥
⎣4⋅a₃₁  2⋅a₃₂     0   ⎦

### 2.5 Invertible matrix
For which values of $t$ the following matrix is not invertible: 
$$ A = 
\begin{bmatrix}
t+3 & -1 & 1\\
5 & t-3 & 2\\
6 & -6 & t+4 \\ 
\end{bmatrix}
$$

In [72]:
#the matrix is invertible when its determinant is equal to 0.

t = symbols('t')
A = Matrix([[t+3,-1,1],[5,t-3,2],[6,-6,t+4]])
A.det()

solve(A.det(),t)

### 2.6 Pseudo inverse of matrix

The pseudo-inverse of a $m\times n$ matrix $A$ is a generalization of a inverse matrix.
For an overdetermined set of linear equations represented by its matrix $A$ (with $m \ge n$),
if A is full column rank, meaning $rank(A) = n \le m$. Therefore, $A^{T}.A$ is not singular and the pseudo-inverse $A^{\dagger}$ is a left inverse of $A$, in the sense that $A^{\dagger}.A = In$
In this case we have the closed-form expresson $A^{\dagger} = (A^{T}. A)^{-1}.A^{T}$.
The solution to the least-squares problem $min_{x} \Vert Ax-y\Vert$, where the minimum norm is $x^{\ast} = A^{\dagger}.y$

Now consider the following linear systems, find the solution using least-square method:

$$
  \begin{cases}
    x+z & = 1.5\\
    x-y & =2.1\\
    x-z & = 0.8\\
    x+y & = 0.6
  \end{cases}
$$

In [83]:
x, y, z = symbols('x, y, z')

In [87]:
a = Matrix([[1,0,1],[1,-1,0],[1,0,-1],[1,1,0]])
b = Matrix([[1.5],[2.1],[0.8],[0.6]])
X = transpose(Matrix([[x,y,z]]))
a,b,X

⎛⎡1  0   1 ⎤  ⎡1.5⎤     ⎞
⎜⎢         ⎥  ⎢   ⎥  ⎡x⎤⎟
⎜⎢1  -1  0 ⎥  ⎢2.1⎥  ⎢ ⎥⎟
⎜⎢         ⎥, ⎢   ⎥, ⎢y⎥⎟
⎜⎢1  0   -1⎥  ⎢0.8⎥  ⎢ ⎥⎟
⎜⎢         ⎥  ⎢   ⎥  ⎣z⎦⎟
⎝⎣1  1   0 ⎦  ⎣0.6⎦     ⎠

In [89]:
A_result = (a.transpose()*a).inv()*(a.transpose())*b
A_result

⎡1.25 ⎤
⎢     ⎥
⎢-0.75⎥
⎢     ⎥
⎣0.35 ⎦